Easy Coding Standard integration, cleanup
bolt/common pull request #21
Opened 2019-01-14 17:17 UTC by bobdenotter

2019-01-15 11:28 UTC, JarJak requested changes

2019-01-15 11:28 UTC, JarJak commented on src/Json.php
> +        if ($data === null && ($json === '' || (json_last_error()) !== JSON_ERROR_NONE)) {
why not use \GuzzleHttp\json_decode() or any other throwing json decorator?

2019-01-15 11:28 UTC, JarJak commented on src/Serialization.php
> +        } catch (\Throwable $e) {
Throwable catches everything, so previous catch is useless

2019-01-15 11:28 UTC, JarJak commented on src/Serialization.php
> +        } catch (\Throwable $e) {
same here

2019-01-15 11:28 UTC, JarJak commented on src/Str.php
> +        return substr_replace($subject, $replace, $pos, \mb_strlen($search));
keep using \ before global functions or not, but please stick with one approach

2019-01-15 11:59 UTC, bobdenotter commented on src/Json.php
> +        if ($data === null && ($json === '' || (json_last_error()) !== JSON_ERROR_NONE)) {
Not sure. This wasn't written by me. Maybe we should eventually, but for now I just wanted to get ECS in, and fix that specific issue

2019-01-15 12:01 UTC, bobdenotter commented on src/Str.php
> +        return substr_replace($subject, $replace, $pos, \mb_strlen($search));
Fair enough.. Do you know if there's a quick-fix for this using ECS?

2019-01-15 13:32 UTC, JarJak commented on src/Str.php
> +        return substr_replace($subject, $replace, $pos, \mb_strlen($search));
Unfortunately not. Maybe there is one, but I don't know the name.

2019-01-16 07:13 UTC, bobdenotter commented on src/Str.php
> +        return substr_replace($subject, $replace, $pos, \mb_strlen($search));
I replaced all instances on one file, and i didn't like how it looked:

```
-\mb_strlen($search) // Eeeewww
```

Reading up on it, I see Symfony decided against doing it, so i think we should follow suit. 

I'll remove the few we have, for consistency.

2019-01-16 07:13 UTC, bobdenotter commented on src/Str.php
> +        return substr_replace($subject, $replace, $pos, \mb_strlen($search));
Link for reference: https://github.com/symfony/symfony/issues/21020

2019-01-16 07:15 UTC, bobdenotter commented on src/Serialization.php
> +        } catch (\Throwable $e) {
Fixed

2019-01-16 09:27 UTC, JarJak approved these changes

2019-01-16 09:27 UTC, JarJak commented on .travis.yml
> +  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
>Error:         No code coverage driver is available

It needs XDebug installed to work :) Otherwise remove coverage report

2019-01-16 09:37 UTC, bobdenotter commented on .travis.yml
> +  - ./vendor/bin/phpunit --coverage-clover=coverage.xml
I was wondering what that was for.. ;-)

Updated!

2019-01-16 09:45 UTC, merged